# Generated by Django 3.2.5 on 2021-08-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='DEFAULT VALUE', max_length=12, null=True)),
                ('last_name', models.CharField(blank=True, default='DEFAULT VALUE', max_length=12, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Binary')], default='DEFAULT VALUE', max_length=8, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, default='DEFAULT VALUE', null=True)),
                ('date_of_birth', models.DateField(blank=True, default='DEFAULT VALUE', null=True)),
                ('phone_number', models.CharField(blank=True, default='DEFAULT VALUE', max_length=10, null=True)),
                ('natioinal_id', models.CharField(blank=True, default='DEFAULT VALUE', max_length=20, null=True)),
                ('contract', models.FileField(blank=True, default='DEFAULT VALUE', null=True, upload_to='files/')),
                ('resume', models.FileField(blank=True, default='DEFAULT VALUE', null=True, upload_to='files/')),
                ('salary', models.PositiveBigIntegerField(blank=True, default='DEFAULT VALUE', null=True)),
                ('profile_pic', models.ImageField(blank=True, default='DEFAULT VALUE', null=True, upload_to='images/')),
                ('syllabus', models.CharField(blank=True, default='DEFAULT VALUE', max_length=15, null=True)),
                ('company', models.CharField(blank=True, default='DEFAULT VALUE', max_length=12, null=True)),
                ('joining_date', models.DateField(blank=True, default='DEFAULT VALUE', null=True)),
            ],
        ),
    ]
