# Generated by Django 3.2.5 on 2021-08-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20210808_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Joining date', null=True),
        ),
    ]
