# Generated by Django 3.2.5 on 2021-08-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20210808_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='joining_date',
        ),
    ]
