# Generated by Django 3.2.5 on 2021-08-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
